@hostname = localhost
@port = 3000
@base_url = http://{{hostname}}:{{port}}/api/users

@id = 6995d087647000d52ed85a07

### Crear usuario
POST {{base_url}}
Content-Type: application/json

{
  "name": "Josep",
  "email": "josep@correo.com",
  "phone": "444456789"
}

### Obtener todos los usuarios
GET {{base_url}}
Content-Type: application/json

### Obtener usuario por su Id
GET {{base_url}}/{{id}}
Content-Type: application/json

### Eliminar usuario por su Id
DELETE {{base_url}}/{{id}}
Content-Type: application/json

### Actualizar usuario
PUT {{base_url}}/{{id}}
Content-Type: application/json

{ 
  "name": "Joseppe actualizado",
  "email": "josepactualizado@correo.com",
  "phone": "696969699"
  }