@hostname = localhost
@port = 3000
@base_url = http://{{hostname}}:{{port}}/api/users

@id = 699315b4a070ad7b9ce525d8

### Crear usuario
POST {{base_url}}
Content-Type: application/json

{
  "name": "Anna"
}

### Obtener todos los usuarios
GET {{base_url}}
Content-Type: application/json

### Obtener usuario por su Id
GET {{base_url}}/{{id}}
Content-Type: application/json

### Eliminar usuario por su Id
DELETE {{base_url}}/{{id}}
Content-Type: application/json

### Actualizar usuario
PUT {{base_url}}/{{id}}
Content-Type: application/json

{ 
  "name": "Pi"
  }