@hostname = localhost
@port = 3000
@base_url = http://{{hostname}}:{{port}}/api/users

@id = 69972698855bf28f25322b16

### Crear usuario
POST {{base_url}}
Content-Type: application/json

{
  "name": "anna",
  "password": "password",
  "email": "anna@correo.com",
  "phone": "123456789"
}

### Obtener todos los usuarios
GET {{base_url}}
Content-Type: application/json

### Obtener usuario por su Id
GET {{base_url}}/{{id}}
Content-Type: application/json

### Eliminar usuario por su Id
DELETE {{base_url}}/{{id}}
Content-Type: application/json

### Actualizar usuario
PUT {{base_url}}/{{id}}
Content-Type: application/json

{ 
  "name": "Joseppe actualizado",
  "email": "josepactualizado@correo.com",
  "phone": "696969699"
  }